Repository JohnFTitor/my_recipe_app, pull requests merged in 2022-05, with the labels that each got.

#17 Login Registration page
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/users/index.html.erb
  config/routes.rb
  db/migrate/20220517162714_create_users.rb
  db/migrate/20220517164249_add_devise_to_users.rb
  db/schema.rb
  spec/helpers/users_helper_spec.rb
  spec/models/user_spec.rb
  spec/requests/users_spec.rb
Labels: enhancement

#18 Create Models and Migrations
  Gemfile
  Gemfile.lock
  app/models/food.rb
  app/models/recipe.rb
  app/models/recipe_food.rb
  app/models/user.rb
  db/migrate/20220517172017_create_recipes.rb
  db/migrate/20220517172638_add_user_ref_to_recipes.rb
  db/migrate/20220517173525_create_foods.rb
  db/migrate/20220517174715_create_recipe_foods.rb
  db/schema.rb
  db/seeds.rb
  spec/models/food_spec.rb
  spec/models/recipe_food_spec.rb
  spec/models/recipe_spec.rb
Labels: enhancement

#20 Create food controller
  app/assets/stylesheets/_foods.scss
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/foods_controller.rb
  app/helpers/food_helper.rb
  app/models/food.rb
  app/views/foods/_form.html.erb
  app/views/foods/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_table.html.erb
  config/routes.rb
  db/migrate/20220517173525_create_foods.rb
  db/schema.rb
  spec/factories/foods.rb
  spec/factories/users.rb
  spec/helpers/food_helper_spec.rb
  spec/models/food_spec.rb
  spec/requests/food_spec.rb
  spec/system/food_spec.rb
Labels: documentation, enhancement, testing

#22 Bugfix/tests
  .stylelintrc.json
  app/assets/stylesheets/_foods.scss
  app/assets/stylesheets/application.bootstrap.scss
  spec/integration/recipes_spec.rb
  spec/models/recipe_spec.rb
  spec/models/user_spec.rb
Labels: bug

#24 Feature/navbar
  app/models/food.rb
  app/views/layouts/application.html.erb
  app/views/shared/_navbar.html.erb
  yarn.lock
Labels: enhancement

#23 Public Recipes
  app/controllers/application_controller.rb
  app/controllers/recipes_controller.rb
  app/models/ability.rb
  app/models/food.rb
  app/models/recipe.rb
  app/models/recipe_food.rb
  app/models/user.rb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  app/views/recipes/show_public_recipes.html.erb
  config/routes.rb
  db/migrate/20220519213218_add_role_to_user.rb
  db/schema.rb
  spec/integration/recipes_spec.rb
  spec/models/recipe_food_spec.rb
  spec/models/recipe_spec.rb
  spec/models/user_spec.rb
  spec/requests/food_spec.rb
  spec/requests/recipes_spec.rb
Labels: documentation, enhancement, testing

#25 General shopping list
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/shared/_navbar.html.erb
  app/views/users/index.html.erb
  config/routes.rb
  spec/integration/users_spec.rb
  spec/models/user_spec.rb
  spec/requests/users_spec.rb
Labels: documentation, enhancement, testing

#27 Feature/recipe creations
  app/assets/stylesheets/_foods.scss
  app/assets/stylesheets/_recipes.scss
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/components/_toggle-button.scss
  app/controllers/foods_controller.rb
  app/controllers/recipe_foods_controller.rb
  app/controllers/recipes_controller.rb
  app/helpers/recipe_food_helper.rb
  app/models/recipe_food.rb
  app/views/foods/index.html.erb
  app/views/recipe_food/destroy.html.erb
  app/views/recipes/_add_ingredient_form.html.erb
  app/views/recipes/show.html.erb
  app/views/shared/_table.html.erb
  config/routes.rb
  spec/helpers/recipe_food_helper_spec.rb
  spec/models/recipe_food_spec.rb
  spec/views/recipe_food/destroy.html.erb_spec.rb
Labels: enhancement, testing
